# Generated by Django 5.0.2 on 2026-02-11 21:24

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('filename', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('transcript', models.TextField(null=True)),
                ('edited_transcript', models.TextField(null=True)),
                ('formatted_text', ckeditor.fields.RichTextField(null=True)),
                ('audio_created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
